apiVersion: container/v1
kind: StepContainerTemplate
inherit: {from: sdk, name: bash.v1}
settings:
  AdditionalCommands:
  - |
    set -eux
    mkdir -p /tmp/helm && \
      cd /tmp/helm && \
      curl -L -o helm.tar.gz https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz && \
      echo "$( curl -sL https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz.sha256 )  helm.tar.gz" | sha256sum -c - && \
      tar -xvzf helm.tar.gz && \
      mv linux-amd64/helm /usr/local/bin/helm && \
      cd - && \
      rm -fr /tmp/helm
